services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.backend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:80"
    depends_on:
      - backend
