services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.backend

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # install deps then launch dev server
    command: >
      sh -c "npm install &&
             npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
